{{- if .Values.persistence.tmp.enabled -}}
{{- if not .Values.persistence.tmp.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "libretranslate.fullname" . }}-tmp
  labels:
    app.kubernetes.io/name: {{ include "libretranslate.name" . }}
    helm.sh/chart: {{ include "libretranslate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: app
{{- if .Values.persistence.tmp.annotations }}
  annotations:
{{ toYaml .Values.persistence.tmp.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.tmp.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.tmp.size | quote }}
{{- if .Values.persistence.tmp.storageClass }}
{{- if (eq "-" .Values.persistence.tmp.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.tmp.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}