apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 6 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
