apiVersion: v2
name: libretranslate
description: Libretranslate Helm chart for Kubernetes
icon: https://media.githubusercontent.com/media/f3k-tech/helm/main/charts/libretranslate/icon.png
type: application
version: 0.3.1
appVersion: "1.5.1"
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Added livelinessProbe to values.
    - kind: added
      description: Added readinessProbe to values.
    - kind: changed
      description: deployment.yaml
    - kind: changed
      description: values.yaml
   