apiVersion: v2
name: libretranslate
description: Libretranslate Helm chart for Kubernetes
icon: https://media.githubusercontent.com/media/f3k-tech/helm/main/charts/libretranslate/icon.png
type: application
version: 0.3.2
appVersion: "1.5.1"
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Default livenessProbe values.
    - kind: changed
      description: Default readinessProbe values.
    - kind: changed
      description: values.yaml
    - kind: added
      description: Instructions for livenessProbe and readinessProbe in the docs. 
    - kind: changed
      description: README.md
   