apiVersion: v2
name: libretranslate
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/f3k-tech/helm/main/charts/libretranslate/icon.png
type: application
version: 0.1.0
appVersion: "1.16.0"
